variable "ami" {}
variable "private_key" {}
variable "public_key" {}
variable "username" {}
variable "myip" {}
variable "rmquser" {}
variable "rmqpass" {}
variable "dbpass" {}
variable "dbuser" {}
variable "dbname" {}
variable "instance_count" {}
variable "vpc_name" {}
variable "zone_1" {}
variable "zone_2" {}
variable "zone_3" {}
variable "vpc_cidr" {}
variable "publicsubcidr_1" {}
variable "publicsubcidr_2" {}
variable "publicsubcidr_3" {}
variable "privatesubcidr_1" {}
variable "privatesubcidr_2" {}
variable "privatesubcidr_3" {}